version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 12
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
     - npm cache clear --force
     - npm install --fix
     - npm run manifest
     - ls
  build:
    commands:
      - npm run manifest
      - ls ./assets
      - npm run generate
      - ls
artifacts:
  files:
    -  '**/*'
  base-directory: 'dist'