version: 0.2
env:
  parameter-store:
    
  exported-variables:
    - S3_BUCKET
phases:
  install: 
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
     - echo $S3_BUCKET
     - npm install --fix
     - npm test
  build:
    commands:
      - npm run build
      - cd dist
  post_build:
    commands:
      - aws s3 sync ./ ${S3_BUCKET}