version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 12
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
     - npm i -s --fix
     - npm run manifest
     - npm test
  build:
    commands:
      - npm run generate
artifacts:
  files:
    -  '**/*'
  base-directory: 'dist'