version: 0.2

phases:
  install: 
    commands:
      - echo ${S3_BUCKET}
      - npm i npm@latest -g
  pre_build:
    commands:
     - npm install --fix
     - npm test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - ./dist