name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: TOKEN="%PASS%",USER="%USER%",REPO="%REPO%" npm run build --if-present
      env:
        PASS: ${{ secrets.TOKEN }}
        USER: ${{ secrets.USER }}
        REPO: ${{ secrets.REPO }}
    - run: npm test
      env:
        CI: true
